version: "3"
volumes:
  ruah-db-data:
      driver: local
  ruah-db-test-data:
    driver: local
services:
  web:
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongodb:mongodb
    volumes:
        - ./:/app
        - /app/node_modules
    env_file: .env
    entrypoint: npm run-script run
  testweb:
    build: .
    volumes:
        - ./:/app
        - /app/node_modules
    links:
        - mongodbtest:mongodbtest
    env_file: .env_test
  mongodbtest:
    image: mongo
    restart: always
    env_file: .env
    volumes:
      - ruah-db-test-data:/data/db
    ports:
      - "27019:27017"
  mongodb:
    image: mongo
    restart: always
    env_file: .env
    volumes:
      - ruah-db-data:/data/db
    ports:
      - "27017:27017"