version: "3"
volumes:
  ruah-db-data:
    driver: local
services:
  web:
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mariadb:mariadb
    volumes:
        - ./:/app
        - /app/node_modules
    env_file: .env
    entrypoint: npm run-script run
  mariadb:
    image: mariadb:latest
    restart: always
    env_file: .env
    ports:
      - 3307:3306
    volumes:
      - ruah-db-data:/var/lib/mysql
